version: '3.8'

services:
  loan-predictor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api:/app/api
      - ./frontend:/app/frontend
      - ./models:/app/models
      - ./data:/app/data  # Mount your data directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s