name: Build and Deploy to Azure

  on:
    push:
      branches:
        - main

  jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          docker login ${{ secrets.loanpredictor.azurecr.io }} -u ${{ secrets.loanpredictor }} -p ${{ secrets.T9YxTjcIadvzg8MAUC7iCjonuFwXWrKhmk5/vmcP3J+ACRCqGlMQ }}
          docker build -t ${{ secrets.loanpredictor.azurecr.io }}/myapp:${{ github.sha }} .
          docker push ${{ secrets.loanpredictor.azurecr.io }}/myapp:${{ github.sha }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'loanpredictorwebapp'
          images: '${{ secrets.loanpredictor.azurecr.io }}/myapp:${{ github.sha }}'