name: Build and Deploy to Azure Web App (Container from ACR)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/loan-prediction-app:${{ github.sha }} -t ${{ secrets.ACR_LOGIN_SERVER }}/loan-prediction-app:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/loan-prediction-app:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/loan-prediction-app:latest
